[package]
name = "cargo-edit-locally"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
cargo = "0.18"
curl = "0.4"
env_logger = { version = "0.4", default-features = false }
git2 = "0.6"
rustc-serialize = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "0.9"
toml = "0.4"
